### ISSUE TITLE
How do i implement timeslice

### ISSUE THREAD

**Issue by sampathkumar7** [Garciat/libvorbis.js#11]
i want data available on specified interval to save in parts.

**Comment by Garciat** [comment]
The library in its current form can only encode PCM data to ogg+vorbis. There are no audio manipulation facilities, nor is it an intended use case for this library.

However, if I'm not mistaken, it should be simple enough to implement time slicing in PCM audio data, because of constant sampling. Essentially: sample index = (audio time [s]) * (sampling rate [1/s]). Then slice the data array with two of those indices.
