### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by fcostarodrigo** [Garciat/libvorbis.js#8]
I get an error when the libvorbis.js script is included in IE11. I am using a virtual machine that I got from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/#downloads to test the website that I am developing in IE11.

IE
Version: v11.0.9600.17420
Update Versions: 11.0.14 (KB3003057)

Error message:
libvorbis.js: 71: `var script = document.currentScript;`
libvorbis.js: 72: `var scriptSrc = script.getAttribute('src');` Unable to get property 'getAttribute' of undefined or null reference.

Typescript code:
libvorbis.head.ts: 103: `const script = <HTMLScriptElement>(<any> document).currentScript;`
libvorbis.head.ts: 104: `const scriptSrc = script.getAttribute('src');`

**Comment by Garciat** [comment]
So sorry for the long delay.

cd24677 introduced a change where you can specify the _absolute URL_ to the libvorbis.js file via a global variable named `LIBVORBISJS_URL`, so that the script won't try to use the `document.currentScript` magic property which is not available in MSIE. It's sort of a lazy hack, but it should work for your case.
